#!/usr/bin/perl
use Image::Magick;
use warnings;
use strict;

&main();

sub main{
	my $image = Image::Magick->new;
	$image->Read("blue.png");

	foreach my $x (0..33){
		my ($r,$g,$b) = $image->GetPixel(x=>$x,y=>0);
		$_ *= 255 for ($r,$g,$b);
		print "$r,$g,$b\n";
	}
}
